var plurals = {
    1: (n) => Number(n > 1),
    2: (n) => Number(n != 1),
    3: (n) => 0,
    4: (n) => Number(n % 10 == 1 && n % 100 != 11 ? 0 : n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 10 || n % 100 >= 20) ? 1 : 2),
    5: (n) => Number(n === 0 ? 0 : n == 1 ? 1 : n == 2 ? 2 : n % 100 >= 3 && n % 100 <= 10 ? 3 : n % 100 >= 11 ? 4 : 5),
    6: (n) => Number((n == 1) ? 0 : (n >= 2 && n <= 4) ? 1 : 2),
    7: (n) => Number(n == 1 ? 0 : n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 10 || n % 100 >= 20) ? 1 : 2),
    8: (n) => Number((n == 1) ? 0 : (n == 2) ? 1 : (n != 8 && n != 11) ? 2 : 3),
    9: (n) => Number(n >= 2),
    10: (n) => Number(n == 1 ? 0 : n == 2 ? 1 : n < 7 ? 2 : n < 11 ? 3 : 4),
    11: (n) => Number((n == 1 || n == 11) ? 0 : (n == 2 || n == 12) ? 1 : (n > 2 && n < 20) ? 2 : 3),
    12: (n) => Number(n % 10 != 1 || n % 100 == 11),
    13: (n) => Number(n !== 0),
    14: (n) => Number((n == 1) ? 0 : (n == 2) ? 1 : (n == 3) ? 2 : 3),
    15: (n) => Number(n % 10 == 1 && n % 100 != 11 ? 0 : n % 10 >= 2 && (n % 100 < 10 || n % 100 >= 20) ? 1 : 2),
    16: (n) => Number(n % 10 == 1 && n % 100 != 11 ? 0 : n !== 0 ? 1 : 2),
    17: (n) => Number(n == 1 || n % 10 == 1 ? 0 : 1),
    18: (n) => Number(0 ? 0 : n == 1 ? 1 : 2),
    19: (n) => Number(n == 1 ? 0 : n === 0 || ( n % 100 > 1 && n % 100 < 11) ? 1 : (n % 100 > 10 && n % 100 < 20 ) ? 2 : 3),
    20: (n) => Number(n == 1 ? 0 : (n === 0 || (n % 100 > 0 && n % 100 < 20)) ? 1 : 2),
    21: (n) => Number(n % 100 == 1 ? 1 : n % 100 == 2 ? 2 : n % 100 == 3 || n % 100 == 4 ? 3 : 0)};

var rules = {
    "ach": {numbers: [1, 2], plural: plurals[1]},
    "af": {numbers: [1, 2], plural: plurals[2]},
    "ak": {numbers: [1, 2], plural: plurals[1]},
    "am": {numbers: [1, 2], plural: plurals[1]},
    "an": {numbers: [1, 2], plural: plurals[2]},
    "ar": {numbers: [0, 1, 2, 3, 11, 100], plural: plurals[5]},
    "arn": {numbers: [1, 2], plural: plurals[1]},
    "ast": {numbers: [1, 2], plural: plurals[2]},
    "ay": {numbers: [1], plural: plurals[3]},
    "az": {numbers: [1, 2], plural: plurals[2]},
    "be": {numbers: [1, 2, 5], plural: plurals[4]},
    "bg": {numbers: [1, 2], plural: plurals[2]},
    "bn": {numbers: [1, 2], plural: plurals[2]},
    "bo": {numbers: [1], plural: plurals[3]},
    "br": {numbers: [1, 2], plural: plurals[1]},
    "bs": {numbers: [1, 2, 5], plural: plurals[4]},
    "ca": {numbers: [1, 2], plural: plurals[2]},
    "cgg": {numbers: [1], plural: plurals[3]},
    "cs": {numbers: [1, 2, 5], plural: plurals[6]},
    "csb": {numbers: [1, 2, 5], plural: plurals[7]},
    "cy": {numbers: [1, 2, 3, 8], plural: plurals[8]},
    "da": {numbers: [1, 2], plural: plurals[2]},
    "de": {numbers: [1, 2], plural: plurals[2]},
    "dev": {numbers: [1, 2], plural: plurals[2]},
    "dz": {numbers: [1], plural: plurals[3]},
    "el": {numbers: [1, 2], plural: plurals[2]},
    "en": {numbers: [1, 2], plural: plurals[2]},
    "eo": {numbers: [1, 2], plural: plurals[2]},
    "es": {numbers: [1, 2], plural: plurals[2]},
    "es_ar": {numbers: [1, 2], plural: plurals[2]},
    "et": {numbers: [1, 2], plural: plurals[2]},
    "eu": {numbers: [1, 2], plural: plurals[2]},
    "fa": {numbers: [1], plural: plurals[3]},
    "fi": {numbers: [1, 2], plural: plurals[2]},
    "fil": {numbers: [1, 2], plural: plurals[1]},
    "fo": {numbers: [1, 2], plural: plurals[2]},
    "fr": {numbers: [1, 2], plural: plurals[9]},
    "fur": {numbers: [1, 2], plural: plurals[2]},
    "fy": {numbers: [1, 2], plural: plurals[2]},
    "ga": {numbers: [1, 2, 3, 7, 11], plural: plurals[1]},
    "gd": {numbers: [1, 2, 3, 20], plural: plurals[1]},
    "gl": {numbers: [1, 2], plural: plurals[2]},
    "gu": {numbers: [1, 2], plural: plurals[2]},
    "gun": {numbers: [1, 2], plural: plurals[1]},
    "ha": {numbers: [1, 2], plural: plurals[2]},
    "he": {numbers: [1, 2], plural: plurals[2]},
    "hi": {numbers: [1, 2], plural: plurals[2]},
    "hr": {numbers: [1, 2, 5], plural: plurals[4]},
    "hu": {numbers: [1, 2], plural: plurals[2]},
    "hy": {numbers: [1, 2], plural: plurals[2]},
    "ia": {numbers: [1, 2], plural: plurals[2]},
    "id": {numbers: [1], plural: plurals[3]},
    "is": {numbers: [1, 2], plural: plurals[1]},
    "it": {numbers: [1, 2], plural: plurals[2]},
    "ja": {numbers: [1], plural: plurals[3]},
    "jbo": {numbers: [1], plural: plurals[3]},
    "jv": {numbers: [0, 1], plural: plurals[1]},
    "ka": {numbers: [1], plural: plurals[3]},
    "kk": {numbers: [1], plural: plurals[3]},
    "km": {numbers: [1], plural: plurals[3]},
    "kn": {numbers: [1, 2], plural: plurals[2]},
    "ko": {numbers: [1], plural: plurals[3]},
    "ku": {numbers: [1, 2], plural: plurals[2]},
    "kw": {numbers: [1, 2, 3, 4], plural: plurals[1]},
    "ky": {numbers: [1], plural: plurals[3]},
    "lb": {numbers: [1, 2], plural: plurals[2]},
    "ln": {numbers: [1, 2], plural: plurals[1]},
    "lo": {numbers: [1], plural: plurals[3]},
    "lt": {numbers: [1, 2, 10], plural: plurals[1]},
    "lv": {numbers: [1, 2, 0], plural: plurals[1]},
    "mai": {numbers: [1, 2], plural: plurals[2]},
    "mfe": {numbers: [1, 2], plural: plurals[1]},
    "mg": {numbers: [1, 2], plural: plurals[1]},
    "mi": {numbers: [1, 2], plural: plurals[1]},
    "mk": {numbers: [1, 2], plural: plurals[1]},
    "ml": {numbers: [1, 2], plural: plurals[2]},
    "mn": {numbers: [1, 2], plural: plurals[2]},
    "mnk": {numbers: [0, 1, 2], plural: plurals[1]},
    "mr": {numbers: [1, 2], plural: plurals[2]},
    "ms": {numbers: [1], plural: plurals[3]},
    "mt": {numbers: [1, 2, 11, 20], plural: plurals[1]},
    "nah": {numbers: [1, 2], plural: plurals[2]},
    "nap": {numbers: [1, 2], plural: plurals[2]},
    "nb": {numbers: [1, 2], plural: plurals[2]},
    "ne": {numbers: [1, 2], plural: plurals[2]},
    "nl": {numbers: [1, 2], plural: plurals[2]},
    "nn": {numbers: [1, 2], plural: plurals[2]},
    "no": {numbers: [1, 2], plural: plurals[2]},
    "nso": {numbers: [1, 2], plural: plurals[2]},
    "oc": {numbers: [1, 2], plural: plurals[1]},
    "or": {numbers: [2, 1], plural: plurals[2]},
    "pa": {numbers: [1, 2], plural: plurals[2]},
    "pap": {numbers: [1, 2], plural: plurals[2]},
    "pl": {numbers: [1, 2, 5], plural: plurals[7]},
    "pms": {numbers: [1, 2], plural: plurals[2]},
    "ps": {numbers: [1, 2], plural: plurals[2]},
    "pt": {numbers: [1, 2], plural: plurals[2]},
    "pt_br": {numbers: [1, 2], plural: plurals[2]},
    "rm": {numbers: [1, 2], plural: plurals[2]},
    "ro": {numbers: [1, 2, 20], plural: plurals[2]},
    "ru": {numbers: [1, 2, 5], plural: plurals[4]},
    "sah": {numbers: [1], plural: plurals[3]},
    "sco": {numbers: [1, 2], plural: plurals[2]},
    "se": {numbers: [1, 2], plural: plurals[2]},
    "si": {numbers: [1, 2], plural: plurals[2]},
    "sk": {numbers: [1, 2, 5], plural: plurals[6]},
    "sl": {numbers: [5, 1, 2, 3], plural: plurals[2]},
    "so": {numbers: [1, 2], plural: plurals[2]},
    "son": {numbers: [1, 2], plural: plurals[2]},
    "sq": {numbers: [1, 2], plural: plurals[2]},
    "sr": {numbers: [1, 2, 5], plural: plurals[4]},
    "su": {numbers: [1], plural: plurals[3]},
    "sv": {numbers: [1, 2], plural: plurals[2]},
    "sw": {numbers: [1, 2], plural: plurals[2]},
    "ta": {numbers: [1, 2], plural: plurals[2]},
    "te": {numbers: [1, 2], plural: plurals[2]},
    "tg": {numbers: [1, 2], plural: plurals[1]},
    "th": {numbers: [1], plural: plurals[3]},
    "ti": {numbers: [1, 2], plural: plurals[1]},
    "tk": {numbers: [1, 2], plural: plurals[2]},
    "tr": {numbers: [1, 2], plural: plurals[1]},
    "tt": {numbers: [1], plural: plurals[3]},
    "ug": {numbers: [1], plural: plurals[3]},
    "uk": {numbers: [1, 2, 5], plural: plurals[4]},
    "ur": {numbers: [1, 2], plural: plurals[2]},
    "uz": {numbers: [1, 2], plural: plurals[1]},
    "vi": {numbers: [1], plural: plurals[3]},
    "wa": {numbers: [1, 2], plural: plurals[1]},
    "wo": {numbers: [1], plural: plurals[3]},
    "yo": {numbers: [1, 2], plural: plurals[2]},
    "zh": {numbers: [1], plural: plurals[3]}
};

export {plurals, rules};
